#!/usr/bin/env bash

GIT_DIR="git-project"
GIT="git --git-dir $GIT_DIR --work-tree ."

help() {
	cat << EOF
Usage: $0 <command>

Commands:

init                Initialize the repository
status              Show the status of the repository
log                 Show the log of the repository
cu <message>        Commit updated changes with message
ca                  Ammend last commit
cp <message>        Commit with message and push
--help              Show this help message
EOF
}

git_init() {
    mkdir -p $GIT_DIR $GIT_DIR/objects $GIT_DIR/refs $GIT_DIR/refs/heads
    echo "ref: refs/heads/master" > $GIT_DIR/HEAD
    echo "Initialized repository"
}


FORMAT_STYLE="%C(yellow)%h %C(bold white)%s%C(reset) %C(dim white)%>(12)%cr%C(reset) \
%C(cyan)%>(8)%aN%C(auto)%d %C(reset)"

case $1 in
    init)
        git_init
        ;;
    status)
        $GIT status -uno
        ;;
    log)
        $GIT log --all --oneline --graph --date=short --format="$FORMAT_STYLE"
        ;;
    u)
        shift
        if [ -z "$1" ]; then
            echo "Message cannot be empty"
            help
            exit 1
        fi
        $GIT add -u && $GIT commit -m "$1"
        ;;
    ca)
        $GIT commit --amend --no-edit --date="$(date)"
        ;;
    cp)
        shift
        if [ -z "$1" ]; then
            echo "Message cannot be empty"
            help
            exit 1
        fi
        $GIT commit -m "$1" && $GIT push
        ;;
    --help)
        help
        ;;
    *)
        $GIT "$@"
        ;;
esac
